spring:
  application:
    name: aims-backend

  # ===== DATABASE =====
  datasource:
    url: jdbc:postgresql://localhost:5435/aims_db?reWriteBatchedInserts=true
    username: aims_user
    password: aims_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000

  # ===== JPA / HIBERNATE =====
  jpa:
    hibernate:
      ddl-auto: update        # creates/updates schema automatically
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # ===== REDIS =====
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

  # ===== MAIL (MOCK — logs to console) =====
  mail:
    host: smtp.gmail.com
    port: 587
    username: aims.noreply@gmail.com
    password: mock-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# ===== SERVER =====
server:
  port: 8080
  servlet:
    context-path: /

# ===== JWT CONFIGURATION =====
app:
  jwt:
    secret: AIMSShopSecretKeyForJWTTokenGeneration2026MustBe256BitsLong!
    expiration-ms: 86400000   # 24 hours

# ===== LOGGING =====
logging:
  level:
    com.aims: INFO
    org.springframework.security: WARN

# ===== PAYPAL =====
paypal:
     client:
        id: AS80_ZkaQeM3a3jW8ymmla5sNV-j0j5wiyh2nvRfhtFn5x1dFZ26UgpWL7yB6eJMW-FUc1-3LQr3LRVB
        secret: EKuym3PlkXCGFh42z5PqEexVgxkj7fOGKW94YM0aA0gVqQNglqIvm3-ul0ibcY5_02uqaw-OTtmHCtqX
     api:
        url: https://api-m.sandbox.paypal.com
