spring:
  application:
    name: aims-backend

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5435/aims_db?reWriteBatchedInserts=true}
    username: ${DB_USERNAME:aims_user}
    password: ${DB_PASSWORD:aims_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000

  data:
    redis:
      url: ${REDIS_URL:redis://localhost:6379}
      timeout: 2000ms

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  mail:
    host: ${MAIL_HOST:sandbox.smtp.mailtrap.io}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

server:
  port: ${PORT:8080}
  servlet:
    context-path: /

app:
  jwt:
    secret: ${JWT_SECRET:AIMSShopSecretKeyForJWTTokenGeneration2026MustBe256BitsLong!}
    expiration-ms: ${JWT_EXPIRATION_MS:86400000}
  frontend:
    url: ${FRONTEND_URL:http://localhost:4200}
  manager:
    email: ${MANAGER_EMAIL:manager@aims.vn}
  admin:
    password: ${ADMIN_PASSWORD:admin123}
  manager-account:
    password: ${MANAGER_PASSWORD:manager123}

logging:
  level:
    com.aims: INFO
    org.springframework.security: WARN
    org.springframework.mail: DEBUG

paypal:
  client:
    id: ${PAYPAL_CLIENT_ID:AS80_ZkaQeM3a3jW8ymmla5sNV-j0j5wiyh2nvRfhtFn5x1dFZ26UgpWL7yB6eJMW-FUc1-3LQr3LRVB}
    secret: ${PAYPAL_CLIENT_SECRET:EKuym3PlkXCGFh42z5PqEexVgxkj7fOGKW94YM0aA0gVqQNglqIvm3-ul0ibcY5_02uqaw-OTtmHCtqX}
  api:
    url: https://api-m.sandbox.paypal.com
  vnd-to-usd-rate: 25000

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME:dlm4q57tz}
  api_key: ${CLOUDINARY_API_KEY:243414491124122}
  api_secret: ${CLOUDINARY_API_SECRET:KCwmgHgBrqvunuCLXwtGSytKGRM}
